// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "github.com/pozedorum/set_pr_reviers_service/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// ClosePR provides a mock function with given fields: pr
func (_m *Repository) ClosePR(pr *entity.PullRequest) error {
	ret := _m.Called(pr)

	if len(ret) == 0 {
		panic("no return value specified for ClosePR")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.PullRequest) error); ok {
		r0 = rf(pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_ClosePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClosePR'
type Repository_ClosePR_Call struct {
	*mock.Call
}

// ClosePR is a helper method to define mock.On call
//   - pr *entity.PullRequest
func (_e *Repository_Expecter) ClosePR(pr interface{}) *Repository_ClosePR_Call {
	return &Repository_ClosePR_Call{Call: _e.mock.On("ClosePR", pr)}
}

func (_c *Repository_ClosePR_Call) Run(run func(pr *entity.PullRequest)) *Repository_ClosePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.PullRequest))
	})
	return _c
}

func (_c *Repository_ClosePR_Call) Return(_a0 error) *Repository_ClosePR_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_ClosePR_Call) RunAndReturn(run func(*entity.PullRequest) error) *Repository_ClosePR_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePR provides a mock function with given fields: pr
func (_m *Repository) CreatePR(pr *entity.PullRequest) error {
	ret := _m.Called(pr)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.PullRequest) error); ok {
		r0 = rf(pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type Repository_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - pr *entity.PullRequest
func (_e *Repository_Expecter) CreatePR(pr interface{}) *Repository_CreatePR_Call {
	return &Repository_CreatePR_Call{Call: _e.mock.On("CreatePR", pr)}
}

func (_c *Repository_CreatePR_Call) Run(run func(pr *entity.PullRequest)) *Repository_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.PullRequest))
	})
	return _c
}

func (_c *Repository_CreatePR_Call) Return(_a0 error) *Repository_CreatePR_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreatePR_Call) RunAndReturn(run func(*entity.PullRequest) error) *Repository_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeam provides a mock function with given fields: team
func (_m *Repository) CreateTeam(team *entity.Team) error {
	ret := _m.Called(team)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Team) error); ok {
		r0 = rf(team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type Repository_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - team *entity.Team
func (_e *Repository_Expecter) CreateTeam(team interface{}) *Repository_CreateTeam_Call {
	return &Repository_CreateTeam_Call{Call: _e.mock.On("CreateTeam", team)}
}

func (_c *Repository_CreateTeam_Call) Run(run func(team *entity.Team)) *Repository_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Team))
	})
	return _c
}

func (_c *Repository_CreateTeam_Call) Return(_a0 error) *Repository_CreateTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreateTeam_Call) RunAndReturn(run func(*entity.Team) error) *Repository_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: user
func (_m *Repository) CreateUser(user *entity.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Repository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user *entity.User
func (_e *Repository_Expecter) CreateUser(user interface{}) *Repository_CreateUser_Call {
	return &Repository_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *Repository_CreateUser_Call) Run(run func(user *entity.User)) *Repository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.User))
	})
	return _c
}

func (_c *Repository_CreateUser_Call) Return(_a0 error) *Repository_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreateUser_Call) RunAndReturn(run func(*entity.User) error) *Repository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindPRByID provides a mock function with given fields: prID
func (_m *Repository) FindPRByID(prID string) (*entity.PullRequest, error) {
	ret := _m.Called(prID)

	if len(ret) == 0 {
		panic("no return value specified for FindPRByID")
	}

	var r0 *entity.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.PullRequest, error)); ok {
		return rf(prID)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.PullRequest); ok {
		r0 = rf(prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindPRByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPRByID'
type Repository_FindPRByID_Call struct {
	*mock.Call
}

// FindPRByID is a helper method to define mock.On call
//   - prID string
func (_e *Repository_Expecter) FindPRByID(prID interface{}) *Repository_FindPRByID_Call {
	return &Repository_FindPRByID_Call{Call: _e.mock.On("FindPRByID", prID)}
}

func (_c *Repository_FindPRByID_Call) Run(run func(prID string)) *Repository_FindPRByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_FindPRByID_Call) Return(_a0 *entity.PullRequest, _a1 error) *Repository_FindPRByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindPRByID_Call) RunAndReturn(run func(string) (*entity.PullRequest, error)) *Repository_FindPRByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPRsByReviewer provides a mock function with given fields: userID
func (_m *Repository) FindPRsByReviewer(userID string) ([]*entity.PullRequest, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindPRsByReviewer")
	}

	var r0 []*entity.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*entity.PullRequest, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []*entity.PullRequest); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindPRsByReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPRsByReviewer'
type Repository_FindPRsByReviewer_Call struct {
	*mock.Call
}

// FindPRsByReviewer is a helper method to define mock.On call
//   - userID string
func (_e *Repository_Expecter) FindPRsByReviewer(userID interface{}) *Repository_FindPRsByReviewer_Call {
	return &Repository_FindPRsByReviewer_Call{Call: _e.mock.On("FindPRsByReviewer", userID)}
}

func (_c *Repository_FindPRsByReviewer_Call) Run(run func(userID string)) *Repository_FindPRsByReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_FindPRsByReviewer_Call) Return(_a0 []*entity.PullRequest, _a1 error) *Repository_FindPRsByReviewer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindPRsByReviewer_Call) RunAndReturn(run func(string) ([]*entity.PullRequest, error)) *Repository_FindPRsByReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// FindTeamByName provides a mock function with given fields: teamName
func (_m *Repository) FindTeamByName(teamName string) (*entity.Team, error) {
	ret := _m.Called(teamName)

	if len(ret) == 0 {
		panic("no return value specified for FindTeamByName")
	}

	var r0 *entity.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.Team, error)); ok {
		return rf(teamName)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.Team); ok {
		r0 = rf(teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindTeamByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTeamByName'
type Repository_FindTeamByName_Call struct {
	*mock.Call
}

// FindTeamByName is a helper method to define mock.On call
//   - teamName string
func (_e *Repository_Expecter) FindTeamByName(teamName interface{}) *Repository_FindTeamByName_Call {
	return &Repository_FindTeamByName_Call{Call: _e.mock.On("FindTeamByName", teamName)}
}

func (_c *Repository_FindTeamByName_Call) Run(run func(teamName string)) *Repository_FindTeamByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_FindTeamByName_Call) Return(_a0 *entity.Team, _a1 error) *Repository_FindTeamByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindTeamByName_Call) RunAndReturn(run func(string) (*entity.Team, error)) *Repository_FindTeamByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function with given fields: userID
func (_m *Repository) FindUserByID(userID string) (*entity.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type Repository_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - userID string
func (_e *Repository_Expecter) FindUserByID(userID interface{}) *Repository_FindUserByID_Call {
	return &Repository_FindUserByID_Call{Call: _e.mock.On("FindUserByID", userID)}
}

func (_c *Repository_FindUserByID_Call) Run(run func(userID string)) *Repository_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_FindUserByID_Call) Return(_a0 *entity.User, _a1 error) *Repository_FindUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindUserByID_Call) RunAndReturn(run func(string) (*entity.User, error)) *Repository_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUsersByTeam provides a mock function with given fields: teamName
func (_m *Repository) FindUsersByTeam(teamName string) ([]*entity.User, error) {
	ret := _m.Called(teamName)

	if len(ret) == 0 {
		panic("no return value specified for FindUsersByTeam")
	}

	var r0 []*entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*entity.User, error)); ok {
		return rf(teamName)
	}
	if rf, ok := ret.Get(0).(func(string) []*entity.User); ok {
		r0 = rf(teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindUsersByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUsersByTeam'
type Repository_FindUsersByTeam_Call struct {
	*mock.Call
}

// FindUsersByTeam is a helper method to define mock.On call
//   - teamName string
func (_e *Repository_Expecter) FindUsersByTeam(teamName interface{}) *Repository_FindUsersByTeam_Call {
	return &Repository_FindUsersByTeam_Call{Call: _e.mock.On("FindUsersByTeam", teamName)}
}

func (_c *Repository_FindUsersByTeam_Call) Run(run func(teamName string)) *Repository_FindUsersByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_FindUsersByTeam_Call) Return(_a0 []*entity.User, _a1 error) *Repository_FindUsersByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindUsersByTeam_Call) RunAndReturn(run func(string) ([]*entity.User, error)) *Repository_FindUsersByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// SetActive provides a mock function with given fields: userID, isActive
func (_m *Repository) SetActive(userID string, isActive bool) error {
	ret := _m.Called(userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(userID, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_SetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActive'
type Repository_SetActive_Call struct {
	*mock.Call
}

// SetActive is a helper method to define mock.On call
//   - userID string
//   - isActive bool
func (_e *Repository_Expecter) SetActive(userID interface{}, isActive interface{}) *Repository_SetActive_Call {
	return &Repository_SetActive_Call{Call: _e.mock.On("SetActive", userID, isActive)}
}

func (_c *Repository_SetActive_Call) Run(run func(userID string, isActive bool)) *Repository_SetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *Repository_SetActive_Call) Return(_a0 error) *Repository_SetActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_SetActive_Call) RunAndReturn(run func(string, bool) error) *Repository_SetActive_Call {
	_c.Call.Return(run)
	return _c
}

// TeamExists provides a mock function with given fields: teamName
func (_m *Repository) TeamExists(teamName string) bool {
	ret := _m.Called(teamName)

	if len(ret) == 0 {
		panic("no return value specified for TeamExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(teamName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Repository_TeamExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamExists'
type Repository_TeamExists_Call struct {
	*mock.Call
}

// TeamExists is a helper method to define mock.On call
//   - teamName string
func (_e *Repository_Expecter) TeamExists(teamName interface{}) *Repository_TeamExists_Call {
	return &Repository_TeamExists_Call{Call: _e.mock.On("TeamExists", teamName)}
}

func (_c *Repository_TeamExists_Call) Run(run func(teamName string)) *Repository_TeamExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_TeamExists_Call) Return(_a0 bool) *Repository_TeamExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_TeamExists_Call) RunAndReturn(run func(string) bool) *Repository_TeamExists_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePR provides a mock function with given fields: pr
func (_m *Repository) UpdatePR(pr *entity.PullRequest) error {
	ret := _m.Called(pr)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePR")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.PullRequest) error); ok {
		r0 = rf(pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePR'
type Repository_UpdatePR_Call struct {
	*mock.Call
}

// UpdatePR is a helper method to define mock.On call
//   - pr *entity.PullRequest
func (_e *Repository_Expecter) UpdatePR(pr interface{}) *Repository_UpdatePR_Call {
	return &Repository_UpdatePR_Call{Call: _e.mock.On("UpdatePR", pr)}
}

func (_c *Repository_UpdatePR_Call) Run(run func(pr *entity.PullRequest)) *Repository_UpdatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.PullRequest))
	})
	return _c
}

func (_c *Repository_UpdatePR_Call) Return(_a0 error) *Repository_UpdatePR_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdatePR_Call) RunAndReturn(run func(*entity.PullRequest) error) *Repository_UpdatePR_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: user
func (_m *Repository) UpdateUser(user *entity.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type Repository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - user *entity.User
func (_e *Repository_Expecter) UpdateUser(user interface{}) *Repository_UpdateUser_Call {
	return &Repository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", user)}
}

func (_c *Repository_UpdateUser_Call) Run(run func(user *entity.User)) *Repository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.User))
	})
	return _c
}

func (_c *Repository_UpdateUser_Call) Return(_a0 error) *Repository_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateUser_Call) RunAndReturn(run func(*entity.User) error) *Repository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
